"""Data models for AI-driven analysis outputs.

Defines dataclasses for stock verdicts, mutual fund recommendations,
market opportunities, and intraday trading setups generated by AWS Bedrock Claude.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class StockVerdict:
    """AI-generated verdict for a stock holding."""

    name: str
    isin: str
    verdict: str  # "buy", "hold", "sell", "exit"
    target_price: float
    stop_loss: float
    rationale: str
    tax_harvest_flag: bool


@dataclass
class MFRecommendation:
    """AI-generated recommendation for a mutual fund SIP."""

    scheme_name: str
    recommendation: str  # "continue", "stop", "switch"
    alternative_scheme: str | None
    rationale: str


@dataclass
class MarketOpportunity:
    """AI-identified market opportunity signal."""

    stock_name: str
    signal_type: str  # "promoter_buying", "multibagger", "fii_accumulation"
    rationale: str


@dataclass
class IntradaySetup:
    """AI-generated intraday trading setup."""

    stock_name: str
    entry_price: float
    target_price: float
    stop_loss: float
    rationale: str


@dataclass
class CrisisOpportunity:
    """Crisis-time buying opportunity identified during market crashes."""

    stock_name: str
    symbol: str
    crisis_category: str  # "DEFENSIVE_QUALITY", "SMART_MONEY_BUY", "OVERSOLD_GEM", "CRISIS_BENEFICIARY"
    current_price: float
    estimated_value: float
    upside_potential_pct: float
    risk_reward: str  # "high", "medium", "low"
    rationale: str
    action: str  # "BUY_NOW", "ACCUMULATE_ON_DIP", "WATCH"


@dataclass
class MultibaggerOpportunity:
    """Future multibagger candidate (3-5 year wealth creation potential)."""

    stock_name: str
    symbol: str
    market_cap_cr: float
    category: str  # "small_cap" or "mid_cap"
    current_price: float
    estimated_target_3yr: float
    upside_potential_pct: float
    multibagger_score: int  # 1-10 conviction score
    growth_drivers: list[str]
    risks: list[str]
    rationale: str
