/**
 * danish-eq Dashboard — Main JavaScript
 *
 * Reads data from JSON files generated by the pipeline:
 * - data/signals.json      (today's picks)
 * - data/candidates.json   (scanner output)
 * - data/portfolio.json    (positions + balances)
 * - data/history.json      (completed trades)
 * - data/universe.json     (instrument list)
 */

// ═══════════════════════════════════════════════════════════
// DATA LAYER
// ═══════════════════════════════════════════════════════════

const DATA_BASE = 'data/';

async function loadJSON(filename) {
    try {
        const resp = await fetch(`${DATA_BASE}${filename}`);
        if (!resp.ok) return null;
        return await resp.json();
    } catch (e) {
        console.warn(`Failed to load ${filename}:`, e.message);
        return null;
    }
}

// ═══════════════════════════════════════════════════════════
// TAB NAVIGATION
// ═══════════════════════════════════════════════════════════

function initTabs() {
    const tabs = document.querySelectorAll('.tab');
    const contents = document.querySelectorAll('.tab-content');

    tabs.forEach(tab => {
        tab.addEventListener('click', () => {
            tabs.forEach(t => { t.classList.remove('active'); t.setAttribute('aria-selected', 'false'); });
            contents.forEach(c => c.classList.remove('active'));

            tab.classList.add('active');
            tab.setAttribute('aria-selected', 'true');
            const target = document.getElementById(`tab-${tab.dataset.tab}`);
            if (target) target.classList.add('active');
        });
    });
}

// ═══════════════════════════════════════════════════════════
// SIGNALS TAB
// ═══════════════════════════════════════════════════════════

function renderSignals(signals) {
    const grid = document.getElementById('signalsGrid');
    if (!signals || signals.length === 0) {
        grid.innerHTML = '<div class="empty-state"><p>No signals yet. Pipeline runs at 21:30 UTC (after US close).</p></div>';
        return;
    }

    // Update meta
    document.getElementById('signalCount').textContent = `${signals.length} picks`;
    const avgConf = (signals.reduce((s, p) => s + (p.confidence || 0), 0) / signals.length).toFixed(1);
    document.getElementById('avgConfidence').textContent = `Avg confidence: ${avgConf}/10`;

    grid.innerHTML = signals.map((pick, idx) => {
        const entry = pick.entry_price || 0;
        const target = pick.target_price || 0;
        const sl = pick.stop_loss_price || 0;
        const risk = entry - sl;
        const rr = risk > 0 ? ((target - entry) / risk).toFixed(1) : '—';
        const conf = pick.confidence || 0;
        const confClass = conf >= 7 ? 'confidence-high' : conf >= 5 ? 'confidence-medium' : 'confidence-low';

        return `
            <div class="signal-card" data-index="${idx}">
                <div class="signal-card-header">
                    <span class="signal-symbol">${pick.symbol}</span>
                    <span class="signal-confidence ${confClass}">${conf}/10</span>
                </div>
                <div class="signal-levels">
                    <div class="level-item">
                        <div class="level-label">Entry</div>
                        <div class="level-value entry">${entry.toFixed(2)}</div>
                    </div>
                    <div class="level-item">
                        <div class="level-label">Target</div>
                        <div class="level-value target">${target.toFixed(2)}</div>
                    </div>
                    <div class="level-item">
                        <div class="level-label">Stop Loss</div>
                        <div class="level-value stoploss">${sl.toFixed(2)}</div>
                    </div>
                </div>
                <div class="signal-rationale-preview">${pick.rationale || 'No rationale provided'}</div>
                <div class="signal-meta">
                    <span class="signal-rr">R:R ${rr}</span>
                    <span>Hold: ${pick.holding_days_estimate || '?'}d</span>
                    <button class="btn-rationale" onclick="showRationale(${idx})">🧠 Full Analysis</button>
                </div>
            </div>
        `;
    }).join('');
}

function showRationale(index) {
    const panel = document.getElementById('rationalePanel');
    const signals = window._currentSignals || [];
    const pick = signals[index];
    if (!pick) return;

    document.getElementById('rationaleSymbol').textContent = pick.symbol;

    const entry = pick.entry_price || 0;
    const target = pick.target_price || 0;
    const sl = pick.stop_loss_price || 0;
    const risk = entry - sl;
    const rr = risk > 0 ? ((target - entry) / risk).toFixed(2) : '—';
    const upside = entry > 0 ? (((target - entry) / entry) * 100).toFixed(1) : '—';
    const downside = entry > 0 ? (((entry - sl) / entry) * 100).toFixed(1) : '—';

    document.getElementById('rationaleBody').innerHTML = `
        <div class="rationale-section">
            <div class="rationale-label">AI Rationale</div>
            <p>${pick.rationale || 'No detailed rationale available.'}</p>
        </div>
        <div class="rationale-section">
            <div class="rationale-label">Trade Setup</div>
            <p>
                <strong>Entry:</strong> ${entry.toFixed(2)} →
                <strong>Target:</strong> ${target.toFixed(2)} (+${upside}%) →
                <strong>Stop:</strong> ${sl.toFixed(2)} (-${downside}%)
            </p>
            <p><strong>Risk:Reward:</strong> 1:${rr}</p>
            <p><strong>Holding Period:</strong> ${pick.holding_days_estimate || '5-15'} trading days</p>
            <p><strong>Confidence:</strong> ${pick.confidence}/10</p>
        </div>
        <div class="rationale-section">
            <div class="rationale-label">Position Sizing (ASK)</div>
            <p>
                Target position: per profile (Rs.50K\u20132L for swing)<br>
                Shares: calculated per profile capital<br>
                Max risk per trade: ${downside}% of position value
            </p>
        </div>
        <div class="rationale-section">
            <div class="rationale-label">Scanner Signals</div>
            <p>${pick.scanner_rationale || pick.rationale || 'Passed RS-First v3 scoring with min threshold 7.'}</p>
        </div>
    `;

    panel.style.display = 'block';
    panel.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

// ═══════════════════════════════════════════════════════════
// PORTFOLIO TAB
// ═══════════════════════════════════════════════════════════

function renderPortfolio(portfolio) {
    if (!portfolio) return;

    const fmt = (v, prefix = '\u20b9') => `${prefix}${(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 0 })}`;

    document.getElementById('portfolioValue').textContent = fmt(portfolio.total_value);
    document.getElementById('cashAvailable').textContent = fmt(portfolio.cash_balance);
    document.getElementById('openPositions').textContent = `${(portfolio.positions || []).length} / 12`;

    const unrealized = portfolio.unrealized_pnl || 0;
    const unrealizedEl = document.getElementById('unrealizedPnl');
    unrealizedEl.textContent = fmt(unrealized);
    unrealizedEl.className = `stat-value ${unrealized >= 0 ? 'positive' : 'negative'}`;

    const todayPnl = portfolio.today_pnl || 0;
    const todayEl = document.getElementById('todayPnl');
    todayEl.textContent = fmt(todayPnl);
    todayEl.className = `stat-value ${todayPnl >= 0 ? 'positive' : 'negative'}`;

    const utilization = portfolio.capital_limit > 0 ? ((portfolio.deployed_capital / portfolio.capital_limit) * 100).toFixed(0) : 0;
    document.getElementById('capitalUtilization').textContent = `${utilization}%`;
    document.getElementById('capitalProgress').style.width = `${Math.min(utilization, 100)}%`;

    // Positions table
    const positions = portfolio.positions || [];
    const tbody = document.getElementById('positionsBody');
    if (positions.length === 0) {
        tbody.innerHTML = '<tr><td colspan="8" class="empty-row">No open positions</td></tr>';
        return;
    }

    tbody.innerHTML = positions.map(pos => {
        const pnlPct = pos.entry_price > 0 ? (((pos.current_price - pos.entry_price) / pos.entry_price) * 100).toFixed(1) : 0;
        const pnlClass = pnlPct >= 0 ? 'positive' : 'negative';
        const statusClass = pnlPct >= 5 ? 'yes' : pnlPct <= -3 ? 'no' : '';
        const status = pnlPct >= 5 ? 'Near Target' : pnlPct <= -3 ? 'Near SL' : 'Active';

        return `
            <tr>
                <td><strong>${pos.symbol}</strong></td>
                <td>${(pos.entry_price || 0).toFixed(2)}</td>
                <td>${(pos.current_price || 0).toFixed(2)}</td>
                <td class="${pnlClass}">${pnlPct > 0 ? '+' : ''}${pnlPct}%</td>
                <td class="no">${(pos.stop_loss || 0).toFixed(2)}</td>
                <td class="yes">${(pos.target || 0).toFixed(2)}</td>
                <td>${pos.days_held || 0}</td>
                <td class="${statusClass}">${status}</td>
            </tr>
        `;
    }).join('');
}

// ═══════════════════════════════════════════════════════════
// SCANNER TAB
// ═══════════════════════════════════════════════════════════

function renderScanner(candidates) {
    if (!candidates || candidates.length === 0) {
        document.getElementById('scannerBody').innerHTML =
            '<tr><td colspan="8" class="empty-row">Run scanner to populate</td></tr>';
        return;
    }

    // Heatmap
    const heatmap = document.getElementById('heatmap');
    heatmap.innerHTML = candidates.slice(0, 80).map(c => {
        const pct = c.pct_5d || c.pct_change_5d || 0;
        let cls = 'neutral';
        if (pct > 5) cls = 'strong-green';
        else if (pct > 3) cls = 'green';
        else if (pct > 1) cls = 'light-green';
        else if (pct < -5) cls = 'strong-red';
        else if (pct < -3) cls = 'red';
        else if (pct < -1) cls = 'light-red';

        return `<div class="heatmap-cell ${cls}" title="${c.symbol}: ${pct > 0 ? '+' : ''}${pct.toFixed(1)}%">${c.symbol}</div>`;
    }).join('');

    // Table
    const tbody = document.getElementById('scannerBody');
    tbody.innerHTML = candidates.map(c => {
        const pct5 = c.pct_5d || c.pct_change_5d || 0;
        const pct20 = c.pct_20d || c.pct_change_20d || 0;
        const fromHigh = c.near_52w_high || c.from_52w_high || 0;
        const pct5Class = pct5 >= 0 ? 'positive' : 'negative';
        const pct20Class = pct20 >= 0 ? 'positive' : 'negative';

        return `
            <tr>
                <td><strong>${c.symbol}</strong></td>
                <td>${c.score || '—'}</td>
                <td>${(c.last_price || 0).toFixed(2)}</td>
                <td class="${pct5Class}">${pct5 > 0 ? '+' : ''}${pct5.toFixed(1)}%</td>
                <td class="${pct20Class}">${pct20 > 0 ? '+' : ''}${pct20.toFixed(1)}%</td>
                <td>${fromHigh.toFixed(1)}%</td>
                <td>${((c.avg_volume_20d || 0) / 1000000).toFixed(1)}M</td>
                <td>${(c.rationale || []).join(', ') || '—'}</td>
            </tr>
        `;
    }).join('');
}

// ═══════════════════════════════════════════════════════════
// RISK TAB
// ═══════════════════════════════════════════════════════════

function renderRisk(portfolio) {
    if (!portfolio) return;

    const dailyLoss = Math.abs(portfolio.today_pnl || 0);
    const totalValue = portfolio.total_value || 174000;
    const lossPct = (dailyLoss / totalValue * 100).toFixed(2);
    const gauge = document.getElementById('dailyLossGauge');
    const gaugeWidth = Math.min((lossPct / 2) * 100, 100);
    gauge.style.width = `${gaugeWidth}%`;
    gauge.className = `gauge-fill ${lossPct > 1.5 ? 'danger' : lossPct > 1 ? 'warning' : ''}`;
    document.getElementById('dailyLossLabel').textContent = `${lossPct}% / 2% max`;

    // Sector exposure
    const positions = portfolio.positions || [];
    const sectors = {};
    positions.forEach(p => {
        const sector = p.sector || 'Unknown';
        sectors[sector] = (sectors[sector] || 0) + (p.value || 0);
    });

    const sectorBars = document.getElementById('sectorBars');
    if (Object.keys(sectors).length === 0) {
        sectorBars.innerHTML = '<div class="sector-row"><span class="sector-name">No positions</span></div>';
    } else {
        const totalPositionValue = Object.values(sectors).reduce((a, b) => a + b, 0);
        sectorBars.innerHTML = Object.entries(sectors)
            .sort((a, b) => b[1] - a[1])
            .map(([name, value]) => {
                const pct = totalPositionValue > 0 ? ((value / totalPositionValue) * 100).toFixed(0) : 0;
                return `
                    <div class="sector-row">
                        <span class="sector-name">${name}</span>
                        <div class="sector-bar"><div class="sector-fill" style="width: ${pct}%"></div></div>
                        <span class="sector-pct">${pct}%</span>
                    </div>
                `;
            }).join('');
    }
}

// ═══════════════════════════════════════════════════════════
// HISTORY TAB
// ═══════════════════════════════════════════════════════════

function renderHistory(history) {
    if (!history || history.length === 0) {
        document.getElementById('historyBody').innerHTML =
            '<tr><td colspan="9" class="empty-row">No completed trades yet</td></tr>';
        return;
    }

    // Stats
    const wins = history.filter(t => (t.pnl_pct || 0) > 0).length;
    const winRate = ((wins / history.length) * 100).toFixed(0);
    document.getElementById('totalTrades').textContent = history.length;
    document.getElementById('winRate').textContent = `${winRate}%`;

    const avgRR = history.reduce((s, t) => s + (t.rr_achieved || 0), 0) / history.length;
    document.getElementById('avgRR').textContent = avgRR.toFixed(1);

    const totalPnl = history.reduce((s, t) => s + (t.pnl_dkk || 0), 0);
    const totalPnlEl = document.getElementById('totalPnl');
    totalPnlEl.textContent = `Rs.${totalPnl.toLocaleString('en-IN')}`;
    totalPnlEl.className = `stat-value ${totalPnl >= 0 ? 'positive' : 'negative'}`;

    // Table
    const tbody = document.getElementById('historyBody');
    tbody.innerHTML = history.map(t => {
        const pnlClass = (t.pnl_pct || 0) >= 0 ? 'positive' : 'negative';
        const outcome = (t.pnl_pct || 0) > 0 ? '✅ Win' : '❌ Loss';

        return `
            <tr>
                <td>${t.date || '—'}</td>
                <td><strong>${t.symbol}</strong></td>
                <td>${(t.entry_price || 0).toFixed(2)}</td>
                <td>${(t.exit_price || 0).toFixed(2)}</td>
                <td class="${pnlClass}">${(t.pnl_pct || 0) > 0 ? '+' : ''}${(t.pnl_pct || 0).toFixed(1)}%</td>
                <td class="${pnlClass}">${(t.pnl_dkk || 0).toLocaleString('en-IN')}</td>
                <td>${t.days_held || '—'}</td>
                <td>${outcome}</td>
                <td>${t.signal_score || '—'}</td>
            </tr>
        `;
    }).join('');

    // Equity curve
    drawEquityCurve(history);
}

function drawEquityCurve(history) {
    const canvas = document.getElementById('equityCanvas');
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const rect = canvas.parentElement.getBoundingClientRect();
    canvas.width = rect.width;
    canvas.height = rect.height;

    // Build cumulative P&L
    let cumulative = portfolio.starting_capital || 100000; // Starting value
    const points = [{ x: 0, y: cumulative }];
    history.forEach((t, i) => {
        cumulative += (t.pnl_dkk || 0);
        points.push({ x: i + 1, y: cumulative });
    });

    if (points.length < 2) return;

    const minY = Math.min(...points.map(p => p.y)) * 0.98;
    const maxY = Math.max(...points.map(p => p.y)) * 1.02;
    const xScale = canvas.width / (points.length - 1);
    const yScale = canvas.height / (maxY - minY);

    // Draw line
    ctx.beginPath();
    ctx.strokeStyle = '#6366f1';
    ctx.lineWidth = 2;
    points.forEach((p, i) => {
        const x = p.x * xScale;
        const y = canvas.height - (p.y - minY) * yScale;
        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
    });
    ctx.stroke();

    // Fill area
    ctx.lineTo(canvas.width, canvas.height);
    ctx.lineTo(0, canvas.height);
    ctx.closePath();
    ctx.fillStyle = 'rgba(99, 102, 241, 0.1)';
    ctx.fill();
}

// ═══════════════════════════════════════════════════════════
// UNIVERSE TAB
// ═══════════════════════════════════════════════════════════

function renderUniverse(universe) {
    if (!universe) {
        // Use hardcoded fallback
        renderUniverseFallback();
        return;
    }

    const tiers = {
        tier1: { el: 'tier1Chips', symbols: universe.tier1_nifty50?.symbols || [] },
        tier2: { el: 'tier2Chips', symbols: universe.tier2_niftynext50?.symbols || [] },
        tier3_dk: { el: 'tier3DkChips', symbols: universe.tier3_defensive?.symbols || [] },
        tier3_eu: { el: 'tier3EuChips', symbols: universe.tier4_momentum?.symbols || [] },
    };

    Object.entries(tiers).forEach(([key, { el, symbols }]) => {
        const container = document.getElementById(el);
        if (container) {
            container.innerHTML = symbols.map(s => `<span class="chip">${s}</span>`).join('');
        }
    });
}

function renderUniverseFallback() {
    const tier1 = ['RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','ITC','SBIN','BHARTIARTL','KOTAKBANK','LT','HCLTECH','BAJFINANCE','ASIANPAINT','MARUTI','AXISBANK','SUNPHARMA','TITAN','ULTRACEMCO','WIPRO','NESTLEIND','NTPC','ONGC','TATASTEEL','JSWSTEEL','POWERGRID','TECHM','ADANIPORTS','COALINDIA','BAJAJFINSV','TATAMOTORS','M&M','CIPLA','DIVISLAB','DRREDDY','HINDALCO','INDUSINDBK','BRITANNIA','HEROMOTOCO','BPCL','UPL','SHREECEM','EICHERMOT','GRASIM','TATACONSUM','BAJAJ-AUTO','SBILIFE','HDFCLIFE','ADANIENT','APOLLOHOSP'];
    const tier2 = ['ABB','ADANIGREEN','AMBUJACEM','AUROPHARMA','BANKBARODA','BOSCHLTD','CANBK','CHOLAFIN','COLPAL','DABUR','DLF','GAIL','GODREJCP','HAL','HAVELLS','HINDPETRO','ICICIPRULI','ICICIGI','INDHOTEL','IOC','IRCTC','IRFC','JIOFIN','JSWENERGY','JINDALSTEL','LTF','LTIM','LICI','LODHA','MARICO','MAXHEALTH','NHPC','NAUKRI','OBEROIRLTY','OFSS','PAGEIND','PERSISTENT','PIDILITIND','PNB','POLYCAB','RECLTD','SBICARD','SIEMENS','SRF','TORNTPHARM','TVSMOTOR','UNIONBANK','VEDL','ZOMATO','ZYDUSLIFE'];
    const tier3 = ['APOLLOHOSP','CIPLA','DIVISLAB','DRREDDY','SUNPHARMA','BIOCON','LUPIN','TORNTPHARM','HINDUNILVR','ITC','NESTLEIND','BRITANNIA','DABUR','MARICO','COLPAL','TATACONSUM','PGHH','GODREJCP','EMAMI','JYOTHYLAB'];
    const tier4 = ['TCS','INFY','HCLTECH','WIPRO','TECHM','HDFCBANK','ICICIBANK','SBIN','KOTAKBANK','AXISBANK','INDUSINDBK','TATASTEEL','JSWSTEEL','HINDALCO','COALINDIA','ONGC','COFORGE','PERSISTENT','MPHASIS','LTIM','BANKBARODA','PNB','FEDERALBNK','IDFCFIRSTB','JINDALSTEL','SAIL','NMDC','VEDL','NATIONALUM'];

    document.getElementById('tier1Chips').innerHTML = tier1.map(s => `<span class="chip">${s}</span>`).join('');
    document.getElementById('tier2Chips').innerHTML = tier2.map(s => `<span class="chip">${s}</span>`).join('');
    document.getElementById('tier3DkChips').innerHTML = tier3.map(s => `<span class="chip">${s}</span>`).join('');
    document.getElementById('tier3EuChips').innerHTML = tier4.map(s => `<span class="chip">${s}</span>`).join('');
}

// ═══════════════════════════════════════════════════════════
// MARKET STATUS
// ═══════════════════════════════════════════════════════════

function updateMarketStatus() {
    const now = new Date();
    const utcH = now.getUTCHours(), utcM = now.getUTCMinutes();
    const istTotalMin = utcH * 60 + utcM + 330; // IST = UTC + 5:30
    const istH = Math.floor(istTotalMin / 60) % 24;
    const istM = istTotalMin % 60;
    const day = now.getUTCDay();
    const el = document.getElementById('marketStatus');

    if (day === 0 || day === 6) {
        el.textContent = '\u25cf NSE Closed (Weekend)';
        el.className = 'market-status';
        return;
    }

    const istMinutes = istH * 60 + istM;
    // NSE: Pre-market 9:00-9:15, Open 9:15-15:30
    if (istMinutes >= 555 && istMinutes <= 930) {
        el.textContent = '\u25cf NSE Open';
        el.className = 'market-status open';
    } else if (istMinutes >= 540 && istMinutes < 555) {
        el.textContent = '\u25cf Pre-Market';
        el.className = 'market-status';
    } else {
        el.textContent = '\u25cf NSE Closed';
        el.className = 'market-status';
    }
}

// ═══════════════════════════════════════════════════════════
// INITIALIZATION
// ═══════════════════════════════════════════════════════════

async function loadAllData() {
    const [signals, candidates, portfolio, history, universe] = await Promise.all([
        loadJSON('signals.json'),
        loadJSON('candidates.json'),
        loadJSON('portfolio.json'),
        loadJSON('history.json'),
        loadJSON('universe.json'),
    ]);

    window._currentSignals = signals || [];

    renderSignals(signals);
    renderScanner(candidates);
    renderPortfolio(portfolio);
    renderRisk(portfolio);
    renderHistory(history);
    renderUniverse(universe);

    // Update timestamp
    document.getElementById('lastUpdate').textContent =
        `Updated: ${new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;

    if (signals && signals.length > 0) {
        const today = new Date().toISOString().split('T')[0];
        document.getElementById('signalDate').textContent = today;
    }
}

// Event listeners
document.addEventListener('DOMContentLoaded', () => {
    initTabs();
    updateMarketStatus();
    setInterval(updateMarketStatus, 60000);
    loadAllData();
    renderUniverseFallback(); // Always show universe even without data file

    // Refresh button
    document.getElementById('btnRefresh').addEventListener('click', loadAllData);

    // Close rationale panel
    document.getElementById('closeRationale').addEventListener('click', () => {
        document.getElementById('rationalePanel').style.display = 'none';
    });

    // Scanner search
    document.getElementById('scannerSearch')?.addEventListener('input', (e) => {
        const query = e.target.value.toLowerCase();
        const rows = document.querySelectorAll('#scannerBody tr');
        rows.forEach(row => {
            const symbol = row.querySelector('td')?.textContent?.toLowerCase() || '';
            row.style.display = symbol.includes(query) ? '' : 'none';
        });
    });
});
